builds:
  - binary: gandi-livedns-cli
    main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: yseto
    name: gandi-livedns-cli
